<?xml version="1.0" encoding="utf-8"?><Database Name="HospitalDataBase" Class="HospitalContexctDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-0MT6QTG;Initial Catalog=HospitalDataBase;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HospitalDataBaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Hospital" Member="Hospitals">
    <Type Name="Hospital">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="payment" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hoursOfWOrk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="yearBirth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>